package com.education.dto;

public class Constants {

    public static String TOKEN_ISSUER = "Lakshminarayana Asula";
    public static String authorization = "Authorization";
    public static String bearerKey = "Bearer ";
    public static String statusCode_Success = "0";
    public static String statusCode_Failure = "1";
    public static String userNameAndPassword_Empty_Error = "UserName and Password should not be empty or null.";
    public static String userNotFound_Error = "User not Found, Invalid UserName or Password.";
    public static String role_PRINCIPAL = "PRINCIPAL";
    public static String role_Administrator = "Administrator";
    public static String role_LECTURER = "LECTURER";
    public static String role_DIRECTOR = "DIRECTOR";
    public static String role_STUDENT = "STUDENT";
    public static String connection_Error = "Connection Error, please try again later.";
    public static String standardAndAmount_Empty_Error = "Standard and Fee amount should not be empty or null.";
    public static String userIdAndOtpValue_Empty_Error = "UserId and Otp should not be empty or null.";
    public static String userIdAndEmailId_Empty_Error = "UserId and Email Id should not empty be or null.";
    public static String OTP_VALID = "Valid OTP.";
    public static String OTP_INVALID = "Invalid OTP.";
    public static String IDSTART_MNG = "MNG";
    public static String IDSTART_YES = "YES";
    public static String userId_Empty_Error = "UserId should not be null or empty.";
    public static String userId_Invalid = "Invalid UserId.";
    public static String userIdEmailId_Mismatch = "UserId and EmailId is not matching with our records.";
    public static String emailSub_ForgotPassword = "Educational | Forgot Password";
    public static String dear = "Dear ";
    public static String newLineSingle = "\n";
    public static String newLineDouble = "\n\n";
    public static String emailMsg_SendOTP = " is your verification code, please DO NOT disclose it to anyone.";
    public static String email_Regards = "Regards, \nEducational Management";
    public static String sendOtp_Msg = "OTP has been sent successfully to ";
    public static String emailSub_UpdatePassword = "Educational | Update Password";
    public static String emailMsg_UpdatePass = "Password has been updated successfully and below are the details DO NOT disclose it to anyone.";
    public static String updatePass_UserId = "UserId : ";
    public static String updatePass_Password = "Password : ";
    public static String updatePass_Success = "Password has been updated successfully.";
    public static String eligible_Login_Success = "Eligible for Login.";
    public static String eligible_Login_Failure = "Not Eligible for Login.";
    public static int tempCount_CoolingPeriod = 3;
    public static int permCount_CoolingPeriod = 3;
    public static String permanent_Block_Msg = "User has been blocked Permanently. To Activate, please contact Administrator.";
    public static String coolingPeriod_Msg = "User is in Cooling period state. Remaining time is ";
    public static String temporary_Block_Msg = "User has been blocked Temporarily. Please try after ";
    public static String invalidPassword_Count = "Invalid Password, ";
    public static String outOf3 = " out of 3. ";
    public static String userExist_Already = "User already exist, USER ID is : ";
    public static String registrationCompleted_Success = "Registration has been completed successfully, USER ID is : ";
    public static String fullNameFatherMotherName_Empty_Error = "FullName, FatherName and MotherName should not be empty or null.";
    public static String emailSub_Registration = "Educational | Registration";
    public static String emailMsg_Reg = "Registration has been completed successfully. \nBelow are the details, DO NOT disclose it to anyone.";
}
