package com.friends.dto;

public class Constants {
    public static String emptyEmpIdBatchNum = "Employee Id and Batch Number should not be empty or null";
    public static String emptyLoginCred = "Employee Id and Password should be empty or null.";
    public static String errorMsg = "Invalid Employee Id or Password.";
    public static String idStart = "YES";
    public static String status_Success = "0";
    public static String status_Failure = "1";
    public static String hr = "HR";
    public static String trainee = "TRAINER";
    public static String employee = "EMPLOYEE";
    public static String stutusTraining = "TRAINING";
    public static String pmo = "PMO";
    public static String empRegError = "Employee information should not be empty.";
    public static String alreadyEmpRegister = "Employee already registered and Employee ID is : ";
    public static String successEmpRegister = "Employee Registered SuccessFully and Employee ID is : ";
    public static String noData = "No Data found";
    public static String emptyBatchNum = "Batch Number should not be empty or null.";
    public static String successEmpInfo = "Successfully Employee information retrieved.";
    public static String otpMsg = " is your verification code. DO NOT disclose it to anyone.";
    public static String invalidEmpStaffId = "Invalid EMPLOYEE or STAFF Id.";
    public static String otpStatus = "sent";
    public static String failureOtpSent = "Failed to send OTP.";
    public static String successOTPSent = "OTP has been sent Successfully!";
    public static String emptyMobileNumberMsg = "Mobile Number should not be empty or null and should be Number only.";
    public static String countryCode_IND = "+91";
    public static String emptyVerifyOtp = "OTP Value and Emp Id Should not be empty or null.";
    public static String invalidFormatOtpValue = "Invalid OTP value, OTP value should be numeric.";
    public static String validOtp = "Valid OTP.";
    public static String invalidOtp = "Invalid OTP, please try again.";
    public static String unverifiedNumber = "The number is unverified.";
    public static String emailSubject_ForgotPassword = "AttendanceTracker | Forgot Password";
    public static String emailSubject_UpdatePassword = "AttendanceTracker | Update Password";
    public static String emailSubject_Greetings = "AttendanceTracker | Welcome";
    public static String emptyEmailId = "Employee Id And Email Id should be empty or null";
    public static String TOKEN_ISSUER = "Lakshminarayana Asula";
    public static String authorization = "Authorization";
    public static String bearerKey = "Bearer ";

    //Batch info
    public static String batch_201 = "MCA201";
    public static String batch_202 = "MCA202";
    public static String batch_203 = "MCA203";
    public static String batch_401 = "CSE401";
    public static String batch_402 = "CSE402";
    public static String saveSuccess = "Attendance saved successfully!";
    public static String saveFailure = "Connection error, please try again.";
    public static String status_Present = "PRESENT";
    public static String statuc_Absent = "ABSENT";
    public static String invalidBatch = "Invalid batch number.";
    public static String alreadySavedAttendance = "Today's Attendance already registered!, please try later.";
    public static String invalidEmpId = "Invalid Employee or Staff ID.";
    public static String invalidKey = "Invalid Key!";
    public static String emailThanks_Msg = "\n\nRegards, \nFriends Application";
    public static String emailReg_Msg = "\n\nRegistration completed Successfully, DO NOT disclose below credentials to anyone.";
    public static String emailMsg_UpdatePass = "\n\nPassword has been updated Successfully, details are given below and DO NOT disclose it to anyone.";
    public static String updatePass_Success = "Password has been updated Successfully!";
    public static String updatePass_EmptyPassword = "Password should not be empty or null";
}
